# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Alien/alpha/alpha

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Alien/alpha/alpha

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Alien/alpha/alpha/CMakeFiles /home/Alien/alpha/alpha//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Alien/alpha/alpha/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named alpha_lib

# Build rule for target.
alpha_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alpha_lib
.PHONY : alpha_lib

# fast build rule for target.
alpha_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alpha_lib.dir/build.make CMakeFiles/alpha_lib.dir/build
.PHONY : alpha_lib/fast

#=============================================================================
# Target rules for targets named cfg_test

# Build rule for target.
cfg_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cfg_test
.PHONY : cfg_test

# fast build rule for target.
cfg_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cfg_test.dir/build.make CMakeFiles/cfg_test.dir/build
.PHONY : cfg_test/fast

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alpha_lib.dir/build.make CMakeFiles/alpha_lib.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alpha_lib.dir/build.make CMakeFiles/alpha_lib.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alpha_lib.dir/build.make CMakeFiles/alpha_lib.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

tests/cfg_test.o: tests/cfg_test.cpp.o
.PHONY : tests/cfg_test.o

# target to build an object file
tests/cfg_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cfg_test.dir/build.make CMakeFiles/cfg_test.dir/tests/cfg_test.cpp.o
.PHONY : tests/cfg_test.cpp.o

tests/cfg_test.i: tests/cfg_test.cpp.i
.PHONY : tests/cfg_test.i

# target to preprocess a source file
tests/cfg_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cfg_test.dir/build.make CMakeFiles/cfg_test.dir/tests/cfg_test.cpp.i
.PHONY : tests/cfg_test.cpp.i

tests/cfg_test.s: tests/cfg_test.cpp.s
.PHONY : tests/cfg_test.s

# target to generate assembly for a file
tests/cfg_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cfg_test.dir/build.make CMakeFiles/cfg_test.dir/tests/cfg_test.cpp.s
.PHONY : tests/cfg_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... alpha_lib"
	@echo "... cfg_test"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... tests/cfg_test.o"
	@echo "... tests/cfg_test.i"
	@echo "... tests/cfg_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

